set(LIB_DIR ${CMAKE_SOURCE_DIR}/bin)
set(EXE_DIR ${CMAKE_SOURCE_DIR}/bin)
set(ARCH_DIR ${CMAKE_SOURCE_DIR}/bin)
set(PDB_DIR ${CMAKE_SOURCE_DIR}/debug_info)
set(PKG_OUTPUT_DIR ${CMAKE_SOURCE_DIR}/pkg)

file(MAKE_DIRECTORY ${LIB_DIR})
file(MAKE_DIRECTORY ${EXE_DIR})
file(MAKE_DIRECTORY ${ARCH_DIR})
file(MAKE_DIRECTORY ${PDB_DIR})
file(MAKE_DIRECTORY ${PKG_OUTPUT_DIR})

set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${LIB_DIR})
set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${EXE_DIR})
set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${ARCH_DIR})
set (CMAKE_PDB_OUTPUT_DIRECTORY ${PDB_DIR})

